import 'dart:convert';
import 'dart:async';
import 'dart:io' as IO;
import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:splashscreen/splashscreen.dart';
import 'package:turnamen_frontend/shared/shared.dart';
import 'package:turnamen_frontend/network_utils/api.dart';
import 'package:image_picker/image_picker.dart';

part 'home_screen.dart';
part 'welcome_screen.dart';
part 'modal_login.dart';
part 'modal_register.dart';
part 'update_screen.dart';
part 'splash_screen.dart';
